# Welcome to first steps of analysis JN

## Постановка задачи и выяснение общей картины.
### Цель этого проекта - анализ рынка труда по направленям Data Sciense и аналитики

In [6]:
# Common imports
import numpy as np
import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# %matplotlib inline

# from tqdm import tnrange, tqdm_notebook
# from random import random, randint

# from globals import path_to_dataset_folder

# to make this notebook's output stable across runs
np.random.seed(13)

print("Setup Complete!")

ModuleNotFoundError: No module named 'globals'

### Этап первый: получение данных
#### Выгрузка собранного датасета

In [7]:
vacancies = pd.read_csv("/home/aleksey/PycharmProjects/My_Web_Scrapper/dataset/" + 'vacancies_data.csv', index_col=0).T
print("Data is ready!")

Data is ready!

In [9]:
# Посмотрим, что из себя представлет наш собранный датасет
vacancies.head()

,0,1,2,3,4,5,6,7,8
0,Data Scientist,ООО Артистраж,Москва,1–3 года,"Полная занятость, полный день",от 120 000 до 170 000 руб. до вычета налогов,Вакансия опубликована 6 октября 2020 в Москве,Обязанности:\nОбработка и аналитика входных да...,Python\nR\nMachine Learning\nComputer Vision\n...
0.1,Data Scientist,ООО РАБЛЗ,Москва,1–3 года,"Полная занятость, удаленная работа",от 150 000 до 210 000 руб. до вычета налогов,Вакансия опубликована 4 октября 2020 в Москве,Наша компания разрабатывает аналитические реше...,Data Mining\nPython\nSQL\nPandas
0.2,Data Scientist,ООО КИБЕРБОРЕЯ,Москва,1–3 года,"Полная занятость, полный день",от 120 000 до 170 000 руб. до вычета налогов,Вакансия опубликована 3 октября 2020 в Москве,Обязанности:\nОбработка и аналитика входных да...,Python\nR\nGit\nMachine Learning\nМашинное обу...
0.3,Data Scientist (ML/CV),ООО Искусственный интеллект,"Москва, 2-я Хуторская улица, 38Ас15",1–3 года,"Полная занятость, полный день",от 180 000 до 200 000 руб. на руки,Вакансия опубликована 5 октября 2020 в Москве,Требования\nЗнание современных алгоритмов ML/D...,Обучение и развитие\nC/C++\nPython 3\nNumPy\nT...
0.4,Data Scientist (Computer Vision),СофтТелематика,"Савеловская, Москва, Вятская улица, 27с20",3–6 лет,"Полная занятость, гибкий график",от 200 000 руб. до вычета налогов,Вакансия опубликована 4 октября 2020 в Москве,СофтТелематика — российский разработчик интелл...,Data Analysis\nmachine learning\ncomputer vision

В целом, кусок собранного датасета выглядит вполне неплохо. Теперь надо бы привести его в адекватный вид. Зададим более осмысленные названия для столбцов. А также нормальные индексы для строк.

In [10]:
vacancies.columns = ['vacancy_title', 'company_name', 'location', 'required_experience', 'employment_mode', 'vacancy_salary',
              'published_date', 'vacancy_description', 'vacancy_tags']

In [12]:
vacancies.index = [idx for idx in range(1,vacancies.shape[0]+1)]

In [14]:
vacancies.head(5)

,vacancy_title,company_name,location,required_experience,employment_mode,vacancy_salary,published_date,vacancy_description,vacancy_tags
1,Data Scientist,ООО Артистраж,Москва,1–3 года,"Полная занятость, полный день",от 120 000 до 170 000 руб. до вычета налогов,Вакансия опубликована 6 октября 2020 в Москве,Обязанности:\nОбработка и аналитика входных да...,Python\nR\nMachine Learning\nComputer Vision\n...
2,Data Scientist,ООО РАБЛЗ,Москва,1–3 года,"Полная занятость, удаленная работа",от 150 000 до 210 000 руб. до вычета налогов,Вакансия опубликована 4 октября 2020 в Москве,Наша компания разрабатывает аналитические реше...,Data Mining\nPython\nSQL\nPandas
3,Data Scientist,ООО КИБЕРБОРЕЯ,Москва,1–3 года,"Полная занятость, полный день",от 120 000 до 170 000 руб. до вычета налогов,Вакансия опубликована 3 октября 2020 в Москве,Обязанности:\nОбработка и аналитика входных да...,Python\nR\nGit\nMachine Learning\nМашинное обу...
4,Data Scientist (ML/CV),ООО Искусственный интеллект,"Москва, 2-я Хуторская улица, 38Ас15",1–3 года,"Полная занятость, полный день",от 180 000 до 200 000 руб. на руки,Вакансия опубликована 5 октября 2020 в Москве,Требования\nЗнание современных алгоритмов ML/D...,Обучение и развитие\nC/C++\nPython 3\nNumPy\nT...
5,Data Scientist (Computer Vision),СофтТелематика,"Савеловская, Москва, Вятская улица, 27с20",3–6 лет,"Полная занятость, гибкий график",от 200 000 руб. до вычета налогов,Вакансия опубликована 4 октября 2020 в Москве,СофтТелематика — российский разработчик интелл...,Data Analysis\nmachine learning\ncomputer vision

Уже лучше. Но всё же есть ещё одна проблема - описание вакансий и тэги на данный момент являются цельными строками, без нормальной разметки. Исправим.

In [16]:
vacancies.vacancy_tags = vacancies.vacancy_tags.str.split(pat="\n")
vacancies.vacancy_description = vacancies.vacancy_description.str.split(pat="\n")
vacancies.head()

,vacancy_title,company_name,location,required_experience,employment_mode,vacancy_salary,published_date,vacancy_description,vacancy_tags
1,Data Scientist,ООО Артистраж,Москва,1–3 года,"Полная занятость, полный день",от 120 000 до 170 000 руб. до вычета налогов,Вакансия опубликована 6 октября 2020 в Москве,"[Обязанности:, Обработка и аналитика входных д...","[Python, R, Machine Learning, Computer Vision,..."
2,Data Scientist,ООО РАБЛЗ,Москва,1–3 года,"Полная занятость, удаленная работа",от 150 000 до 210 000 руб. до вычета налогов,Вакансия опубликована 4 октября 2020 в Москве,[Наша компания разрабатывает аналитические реш...,"[Data Mining, Python, SQL, Pandas]"
3,Data Scientist,ООО КИБЕРБОРЕЯ,Москва,1–3 года,"Полная занятость, полный день",от 120 000 до 170 000 руб. до вычета налогов,Вакансия опубликована 3 октября 2020 в Москве,"[Обязанности:, Обработка и аналитика входных д...","[Python, R, Git, Machine Learning, Машинное об..."
4,Data Scientist (ML/CV),ООО Искусственный интеллект,"Москва, 2-я Хуторская улица, 38Ас15",1–3 года,"Полная занятость, полный день",от 180 000 до 200 000 руб. на руки,Вакансия опубликована 5 октября 2020 в Москве,"[Требования, Знание современных алгоритмов ML/...","[Обучение и развитие, C/C++, Python 3, NumPy, ..."
5,Data Scientist (Computer Vision),СофтТелематика,"Савеловская, Москва, Вятская улица, 27с20",3–6 лет,"Полная занятость, гибкий график",от 200 000 руб. до вычета налогов,Вакансия опубликована 4 октября 2020 в Москве,[СофтТелематика — российский разработчик интел...,"[Data Analysis, machine learning, computer vis..."

Вот теперь намного лучше! С этим уже можно работать.

Чтобы не испортить полученный датасет, сделаем его копию и работать далее будем с ней.

In [17]:
vacancies_df = vacancies.copy()

In [18]:
vacancies_df.head()

,vacancy_title,company_name,location,required_experience,employment_mode,vacancy_salary,published_date,vacancy_description,vacancy_tags
1,Data Scientist,ООО Артистраж,Москва,1–3 года,"Полная занятость, полный день",от 120 000 до 170 000 руб. до вычета налогов,Вакансия опубликована 6 октября 2020 в Москве,"[Обязанности:, Обработка и аналитика входных д...","[Python, R, Machine Learning, Computer Vision,..."
2,Data Scientist,ООО РАБЛЗ,Москва,1–3 года,"Полная занятость, удаленная работа",от 150 000 до 210 000 руб. до вычета налогов,Вакансия опубликована 4 октября 2020 в Москве,[Наша компания разрабатывает аналитические реш...,"[Data Mining, Python, SQL, Pandas]"
3,Data Scientist,ООО КИБЕРБОРЕЯ,Москва,1–3 года,"Полная занятость, полный день",от 120 000 до 170 000 руб. до вычета налогов,Вакансия опубликована 3 октября 2020 в Москве,"[Обязанности:, Обработка и аналитика входных д...","[Python, R, Git, Machine Learning, Машинное об..."
4,Data Scientist (ML/CV),ООО Искусственный интеллект,"Москва, 2-я Хуторская улица, 38Ас15",1–3 года,"Полная занятость, полный день",от 180 000 до 200 000 руб. на руки,Вакансия опубликована 5 октября 2020 в Москве,"[Требования, Знание современных алгоритмов ML/...","[Обучение и развитие, C/C++, Python 3, NumPy, ..."
5,Data Scientist (Computer Vision),СофтТелематика,"Савеловская, Москва, Вятская улица, 27с20",3–6 лет,"Полная занятость, гибкий график",от 200 000 руб. до вычета налогов,Вакансия опубликована 4 октября 2020 в Москве,[СофтТелематика — российский разработчик интел...,"[Data Analysis, machine learning, computer vis..."

In [23]:
# Посмотрим, что там у нас по зарплатам! 
vacancies_df.vacancy_salary.value_counts()

з/п не указана                                  146
от 150 000 руб. на руки                           2
от 120 000 до 170 000 руб. до вычета налогов      2
от 120 000 до 160 000 руб. на руки                1
от 180 000 до 200 000 руб. на руки                1
от 200 000 руб. до вычета налогов                 1
от 150 000 до 210 000 руб. до вычета налогов      1
до 150 000 руб. на руки                           1
до 100 000 руб. до вычета налогов                 1
от 120 000 до 200 000 руб. на руки                1
до 200 000 руб. на руки                           1
от 200 000 до 280 000 руб. до вычета налогов      1
до 500 000 руб. до вычета налогов                 1
до 130 000 руб. до вычета налогов                 1
от 120 000 до 150 000 руб. на руки                1
Name: vacancy_salary, dtype: int64

Не густо - информации по зарплатам в явном виде исчезающе мало.